baseURL = 'https://tranhap.github.io/TranHapBlog/'
languageCode = 'en-us'
title = 'Tran Blog'
theme = 'PaperMod'

params:
  homeInfoParams:
    Title: Hello there!
    Content: I just love writing. I hope that you love it, too!
