name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --baseURL "${{ secrets.BASE_URL }}"

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir built-site 
          cp -R public/* built-site/
          cd built-site
          git init
          git add .
          git commit -m 'Updated site'
          git remote add origin https://github.com/TranHap/TranHapBlog.git 
          git checkout -b gh-pages
          git push origin gh-pages --force
